### ISSUE TITLE
How to get ID and UniqueID to burn firmware 

### ISSUE THREAD

**Issue by KaranBurhanpurkar78** [ajumalp/Smart-Home#2]
Thanks for the code.

Can someone please tell me how can I get the DeviceID and UniqueID to burn the firmware into esp8266. 

Thank You

**Comment by ajumalp** [comment]
Hi,

Thanks for your interest in the project :-) 

Currently I didn't implement any UI to get the Device ID and UniqueID. You need to get it from the devices table as below. 

![](https://raw.githubusercontent.com/ajumalp/Smart-Home/master/Other/Images/Screenshots/get-device-id-uniqueid.png)

Please read the [**How to program devices**](https://github.com/ajumalp/Smart-Home/wiki/How-to-program-Devices) page for more details

**Comment by ajumalp** [comment]
HI,

I've quickly added an option to get the Device details, by clicking the Device as below. Hope this will help for now 

<table>
   <tr>
      <th>
         <img src="https://raw.githubusercontent.com/ajumalp/Smart-Home/master/Other/Images/Screenshots/device-show-details-popup.jpeg" height=25%/>
      </th>
      <th>
         <img src="https://raw.githubusercontent.com/ajumalp/Smart-Home/master/Other/Images/Screenshots/device-details.popup.jpg" height=25%/>
      </th>
   </tr>
</table>

**Comment by leomuguchia** [comment]
hey how is this thing run. ive been trying to set it up but it does nothing. i mean i cant add devices, it doesnt seem to be starting as it shold because it opens directly to the home page while i thought i was going to log in first. also i tried adding devices it just says connection failed, connection refused yet xampp is running ok
